#pragma once

#include "stm32xx_hal.h"

/* Status LEDs */

#define HEARTBEAT_LED_PORT GPIOC
#define HEARTBEAT_LED_PIN GPIO_PIN_11

#define SUPPBAT_FAULT_PORT GPIOC
#define SUPPBAT_FAULT_PIN GPIO_PIN_10

#define LSOM_HEARTBEAT_LED_PORT GPIOC
#define LSOM_HEARTBEAT_LED_PIN GPIO_PIN_3

/* Low Voltage Enable GPIO */ 
#define LV_EN_SUPP_PORT GPIOC
#define LV_EN_SUPP_PIN GPIO_PIN_2

#define LV_EN_POWERSUPPLY_PORT GPIOC
#define LV_EN_POWERSUPPLY_PIN GPIO_PIN_0

/* LTC4421 GPIO */
#define LTC4421_SHDN_PORT GPIOC
#define LTC4421_SHDN_PIN GPIO_PIN_12

#define LTC4421_CHANNEL1_SELECTED_PORT GPIOD
#define LTC4421_CHANNEL1_SELECTED_PIN GPIO_PIN_2

#define LTC4421_CHANNEL2_SELECTED_PORT GPIOB
#define LTC4421_CHANNEL2_SELECTED_PIN GPIO_PIN_0

#define LTC4421_VALID1_SELECTED_PORT GPIOC
#define LTC4421_VALID1_SELECTED_PIN GPIO_PIN_4

#define LTC4421_VALID2_SELECTED_PORT GPIOB
#define LTC4421_VALID2_SELECTED_PIN GPIO_PIN_12

#define LTC4421_FAULT1_PORT GPIOC
#define LTC4421_FAULT1_PIN GPIO_PIN_5

#define LTC4421_FAULT2_PORT GPIOC
#define LTC4421_FAULT2_PIN GPIO_PIN_9


#ifdef LSOM_U // LSOM U version
    #define USB_UART_CLOCK_PORT GPIOC
    #define USB_UART_TX GPIO_PIN_10
    #define USB_UART_RX GPIO_PIN_11
#elif LSOM_S // LSOM S version
    #define USB_UART_CLOCK_PORT GPIOB
    #define USB_UART_TX GPIO_PIN_10
    #define USB_UART_RX GPIO_PIN_11
#endif /* USB UART */