M48
; DRILL file {KiCad 9.0.6} date 2026-04-26T16:58:41-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-26T16:58:41-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0335
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
%
G90
G05
T1
X2.9213Y-3.7953
X2.9213Y-4.2126
T2
X0.722Y-3.4547
X0.7248Y-2.8642
M30
