#pragma once

#include "stm32xx_hal.h"

#define HEARTBEAT_LED_PORT GPIOC
#define HEARTBEAT_LED_PIN GPIO_PIN_3

#define SUPPBAT_FAULT_PORT GPIOC
#define SUPPBAT_FAULT_PIN GPIO_PIN_10

#define LTC4421_SHDN_PORT GPIOC
#define LTC4421_SHDN_PIN GPIO_PIN_12