# .gemini/config.yaml
code_review:
  disable: false
  
  ignore_patterns:
    - "**/*.kicad_pcb"
    - "**/*.kicad_sch"
    - "**/*.kicad_pro"
    - "**/*.kicad_dru"
    - "**/*.kicad_prl"
    - "**/fp-lib-table"
    - "**/sym-lib-table"
    - "**/*.bak"
    - "**/plots/**"
    - "**/gerbers/**"